version: '3'
services:
    nginx:
        container_name: api-nginx
        build:
            context: ./docker/nginx
            dockerfile: /Dockerfile
        image: 'iot-nginx'
        restart: unless-stopped
        tty: true
        volumes:
            - './docker/conf/nginx/nginx.conf:/etc/nginx/nginx.conf'
        networks:
            - iot
    php-fpm:
        container_name: api-php
        build:
            context: ./docker/php
            dockerfile: /Dockerfile
        volumes:
            - './:/var/www'
        image: 'iot-api:latest'
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        networks:
            - iot
networks:
    iot:
        external: true
