version: '3'
services:
    nginx:
        container_name: api-nginx
        build:
            context: .
            dockerfile: docker/nginx/dockerfile
        image: 'collectandverything-nginx'
        restart: unless-stopped
        tty: true
        volumes:
            - '.docker/conf/nginx/nginx.conf:/etc/nginx/nginx.conf'
        networks:
            - app-network
    php-fpm:
        container_name: api-php
        build:
            context: .
            dockerfile: docker/php/dockerfile
        volumes:
            - './:/var/www'
        image: 'collectandverything-api:latest'
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        networks:
            - collectandverything
networks:
    collectandverything:
        external: true
